# Generated by Django 4.2.5 on 2023-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_rename_nmae_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1993-02-22"),
            preserve_default=False,
        ),
    ]
